table/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', SubPostListView.as_view(), name='post_list'),
    path('create/', addTodo, name='main'),
    path('complete/<todo_id>', completeTodo, name='complete'),
    path('deletecomplete', deleteCompleted, name='deletecomplete'),
    path('deleteall', deleteAll, name='deleteall'),
    path('filter/', SearchResultsView.as_view(), name='filter'),
    path('changestatus/<todo_id>', changeStatus, name='change_status'),
    path('export/csv/$', export_users_csv, name='export_users_csv'),

]

test_two_tables/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('table.urls'))
]

table/forms.py
from django import forms
from .models import Post


class CreateField(forms.ModelForm):
    date = forms.CharField(max_length=255,
                           widget=forms.TextInput(
                               attrs={'class': 'form-control datepicker-here', 'data-multiple-dates': '100',
                                      'aria-label': 'Todo', 'data-multiple-dates-separator': ', ',
                                      'data-position': 'top left'}))

    class Meta:
        model = Post
        fields = ['choice', 'text', 'date']



class NameForm(forms.Form):
    author_name = forms.CharField(max_length=100)
    text = forms.CharField(max_length=255)
    post_dates = forms.CharField(max_length=255)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'css/github-gist.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/datepicker.min.css' %}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{% static 'js/datepicker.js' %}"></script>
    <script src="{% static 'js/i18n/datepicker.en.js' %}"></script>
    <script src="{% static 'js/logger.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/test.js' %}"></script>
    <title>Реклама</title>
</head>
<body>
<header class="header">

    <nav class="navbar navbar-expand-lg navbar-dark">
{#        <a class="navbar-brand" href="{% url 'post_list' %}">Logo</a>#}
{#        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"#}
{#                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'post_list' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'main' %}">Добавить объявление</a>
                </li>
                {% if user.is_staff %}
                    <li>
                        <a href="{% url 'export_users_csv' %}" class="nav-link active">Выгрузка</a>
                    </li>
                {% endif %}
            {% if user.is_staff %}

                {% endif %}
            </ul>
            <ul class="navbar-nav float-right">
                <li>
                    <p class="nav-link active">{{ user.username }}</p>

                </li>
                <li class="nav-item">
                    <a class="nav-link active btn btn-primary" href="{% url 'logout' %}">Выход</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="container-fluid">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>
<script async defer id="github-bjs" src="https://buttons.github.io/buttons.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <script language="JavaScript">
        function toggle(source) {
            checkboxes = document.getElementsByName('foo');
            for (var checkbox in checkboxes)
                checkbox.checked = source.checked;
        }
    </script>


    <table class="table table-hover ">
        <thead>
        <tr>
            <th width="10px"><input type="checkbox" id="chkDelete" onClick="toggle(this)"/></th>
            <th width="50px">№</th>
            <th width="190px">Дата создания</th>
                <th>Автор</th>
            <th width="120px">Телеканал</th>
            <th width="400px">Текст</th>
            <th width="200px">Дата проката</th>
            <th width="50px" style="font-size: 13px;">Кол. дней</th>
            <th width="50px" style="font-size: 13px;">Кол. симв</th>
            <th width="100px">Сумма</th>
            <th width="100px">Статус</th>
            {% if user.is_staff %}
                <th>Change</th>
            {% endif %}

        </tr>
        </thead>
        <tbody>
        {% for text in object_list %}
            {% if text.complete %}
                <tr class="todo-completed">
                    <td><input type="checkbox" name="foo" id=""
                               onclick="location.href = '{% url 'complete' text.id %}'" checked></td>
                    <td>{{ text.id }}</td><!-- № текста-->
                    <td>{{ text.order_date }}</td> <!--Дата создания-->

                        <td>
                            {{ text.posts.author }}
                        </td>

                    <td>{{ text.choice }}</td> <!-- Телеканал -->
                    <td style="text-align:left;">{{ text.text }}</td> <!-- Текст -->
                    <td>{{ text.post_dates }}</td><!--Дата проката-->
                    <td>{{ text.quantity_days }}</td> <!--Количество дней-->
                    <td>{{ text.quantity_symbols }}</td> <!--Количество символов-->
                    <td>{{ text.total_price }} сом</td> <!--Сумма -->
                    <td>{{ text.reception }}</td>
                    {% if user.is_staff %}
                        <td>
                            <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}" type="button"
                               class="btn btn-dark">
                                Change
                            </a>
                        </td>
                    {% endif %}
                </tr>
            {% else %}
                <tr class="todo-completed">
                    <td><input type="checkbox" name="foo" id=""
                               onclick="location.href = '{% url 'complete' text.id %}'"></td>
                    <td>{{ text.id }}</td><!-- № текста-->
                    <td>{{ text.order_date }}</td> <!--Дата создания-->

                        <td>
                            {{ text.author }}
                        </td>

                    <td>{{ text.choice }}</td> <!-- Телеканал -->
                    <td style="text-align:left;">{{ text.text }}</td> <!-- Текст -->
                    <td>{{ text.post_dates }}</td><!--Дата проката-->
                    <td>{{ text.quantity_days }}</td> <!--Количество дней-->
                    <td>{{ text.quantity_symbols }}</td> <!--Количество символов-->
                    <td>{{ text.total_price }} сом</td> <!--Сумма -->
                    <td>{{ text.reception }}</td>
                    {% if user.is_staff %}
                        <td>
                            <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}" type="button"
                               class="btn btn-dark">
                                Change
                            </a>
                        </td>
                    {% endif %}
                </tr>

            {% endif %}

        {% endfor %}
        </tbody>
    </table>
    <footer>
        <div class="col-lg-12">
            <nav class="left-nav">
                <ul class="pagination justify-content-center pagination-sm ">
                    <li class="page-item">
                        {% if articles.has_previous %}
                            <a class="link-btn btn btn-primary"
                               href="?page={{ articles.previous_page_number }}">Пред.</a>
                        {% endif %}

                    </li>


                    {% for num in articles.paginator.page_range %}
                        {% if num == articles.number %}
                            <li class="page-item"><span class="link-button btn btn-dark"><b>{{ num }}</b></span></li>
                        {% else %}
                            <li class="page-item"><a class="link-button btn btn-primary"
                                                     href="?page={{ num }}"> {{ num }}</a></li>
                        {% endif %}
                    {% endfor %}



                    <li class="page-item">
                        {% if articles.has_next %}
                            <a class="link-btn btn btn-primary" href="?page={{ articles.next_page_number }}">След.</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>


            <div class="btn-toolbar rigt-nav">
                <div class="btn-group">
                    <a href="{% url 'deletecomplete' %}">
                        <button type="button" class="btn btn-dark">
                            Удалить выделенные
                        </button>
                    </a>
                </div>
                <div id="pnlDeleteAll" class="btn-group dlt-btn">

                    <a href="{% url 'deleteall' %}">
                        <button type="button" class="btn btn-dark">
                            Удалить все
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script>
        function toggle() {
            var div = document.getElementById('pnlDeleteAll');
            if (this.checked)
                div.style.display = 'block';
            else
                div.style.display = 'none'
        }

        document.getElementById('chkDelete').onchange = toggle;
    </script>

    <script>
        function toggle(source) {
            checkboxes = document.getElementsByName('foo');
            for (var i = 0, n = checkboxes.length; i < n; i++) {
                checkboxes[i].checked = source.checked;
            }
        }
    </script>
{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% block title %}
    <h1>Main</h1>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div style="margin-top:30px;">
                <form method="post" action="">
                    {% csrf_token %}
                    <h5>Канал: </h5>{{ form.choice }}
                    <hr>
                    <h5>Текст сообщения: </h5>{{ form.text }}
                    <hr>
                    {{ form.date}}
                    <hr>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block content %}
    <script language="JavaScript">
        function toggle(source) {
            checkboxes = document.getElementsByName('foo');
            for (var checkbox in checkboxes)
                checkbox.checked = source.checked;
        }
    </script>
{{ User }}
    {% if user.is_staff %}
        <form action="{% url 'filter' %}" method="get">
{#        {% csrf_token %}#}
{#            <input name="q" type="text" placeholder="Поиск...">#}
            <input name="text" type="text" placeholder="Поиск по тексту" class="form-control form2">
            <input name="author" type="text" placeholder="Поиск по автору" class="form-control form2">
            <input name="posts" placeholder="Поиск по дате" class="form-control datepicker-here form2" data-multiple-dates="100" aria-label="Todo" data-multiple-dates-separator=", " data-position="bottom left" maxlength="255" id="id_date">
            <button type="submit" class="btn btn-primary">Фильтр</button>
        </form>

    {% endif %}
    <table class="table table-hover ">
        <thead>
        <tr>
            <th width="10px"><input type="checkbox" id="chkDelete" onClick="toggle(this)"/></th>
            <th width="50px">№</th>
            <th width="190px">Дата создания</th>
            {% if user.is_staff %}
                <th>Автор</th>
            {% endif %}
            <th width="120px">Телеканал</th>
            <th width="400px">Текст</th>
            <th width="200px">Дата проката</th>
            <th width="50px" style="font-size: 13px;">Кол. дней</th>
            <th width="50px" style="font-size: 13px;">Кол. симв</th>
            <th width="100px">Сумма</th>
            {% if user.is_staff %}
                <th>Статус</th>
            {% endif %}

        </tr>
        </thead>
        <tbody>

        {% for text in object_list reversed %}
            {% if text.reception == False %}
                {% if text.complete %}
                    <tr class="todo-completed">
                        <td><input type="checkbox" name="foo" id=""
                                   onclick="location.href = '{% url 'complete' text.id %}'" checked></td>
                        <td>{{ text.id }}</td><!-- № текста-->
                        <td>{{ text.order_date }}</td> <!--Дата создания-->
                        {% if user.is_staff %}
                            <td>
                                {{ text.author }}
                            </td>
                        {% endif %}

                        <td>{{ text.choice }}</td> <!-- Телеканал -->
                        <td style="text-align:left;">{{ text.text }}</td> <!-- Текст -->
                        <td>{{ text.post_dates }}</td><!--Дата проката-->
                        <td>{{ text.quantity_days }}</td> <!--Количество дней-->
                        <td>{{ text.quantity_symbols }}</td> <!--Количество символов-->
                        <td>{{ text.total_price }} сом</td> <!--Сумма -->
                        {% if user.is_staff %}
                            <td>
                                {% if text.reception == False %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-dark">
                                        Не подтвержден
                                    </a>
                                {% else %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-success">
                                        Подтвержден
                                    </a>
                                {% endif %}
                            </td>
                        {% endif %}
                    </tr>
                {% else %}
                    <tr class="todo-completed">
                        <td><input type="checkbox" name="foo" id=""
                                   onclick="location.href = '{% url 'complete' text.id %}'"></td>
                        <td>{{ text.id }}</td><!-- № текста-->
                        <td>{{ text.order_date }}</td> <!--Дата создания-->
                        {% if user.is_staff %}
                            <td>
                                {{ text.author }}
                            </td>
                        {% endif %}
                        <td>{{ text.choice }}</td> <!-- Телеканал -->
                        <td style="text-align:left;">{{ text.text }}</td> <!-- Текст -->
                        <td>{{ text.post_dates }}</td><!--Дата проката-->
                        <td>{{ text.quantity_days }}</td> <!--Количество дней-->
                        <td>{{ text.quantity_symbols }}</td> <!--Количество символов-->
                        <td>{{ text.total_price }} сом</td> <!--Сумма -->
                        {% if user.is_staff %}
                            <td>
                                {% if text.reception == False %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-dark">
                                        Не подтвержден
                                    </a>
                                {% else %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-success">
                                        Подтвержден
                                    </a>
                                {% endif %}
                            </td>
                        {% endif %}
                    </tr>

                {% endif %}
            {% elif user.is_staff %}
                {% if text.complete %}
                    <tr class="todo-completed">
                        <td><input type="checkbox" name="foo" id=""
                                   onclick="location.href = '{% url 'complete' text.id %}'" checked></td>
                        <td>{{ text.id }}</td><!-- № текста-->
                        <td>{{ text.order_date }}</td> <!--Дата создания-->
                        {% if user.is_staff %}
                            <td>
                                {{ text.author }}
                            </td>
                        {% endif %}

                        <td>{{ text.choice }}</td> <!-- Телеканал -->
                        <td style="text-align:left;">{{ text.text }}</td> <!-- Текст -->
                        <td>{{ text.post_dates }}</td><!--Дата проката-->
                        <td>{{ text.quantity_days }}</td> <!--Количество дней-->
                        <td>{{ text.quantity_symbols }}</td> <!--Количество символов-->
                        <td>{{ text.total_price }} сом</td> <!--Сумма -->
                        {% if user.is_staff %}
                            <td>
                                {% if text.reception == False %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-dark">
                                        Не подтвержден
                                    </a>
                                {% else %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-success">
                                        Подтвержден
                                    </a>
                                {% endif %}
                            </td>
                        {% endif %}
                    </tr>
                {% else %}
                    <tr class="todo-completed">
                        <td><input type="checkbox" name="foo" id=""
                                   onclick="location.href = '{% url 'complete' text.id %}'"></td>
                        <td>{{ text.id }}</td><!-- № текста-->
                        <td>{{ text.order_date }}</td> <!--Дата создания-->
                        {% if user.is_staff %}
                            <td>
                                {{ text.author }}
                            </td>
                        {% endif %}
                        <td>{{ text.choice }}</td> <!-- Телеканал -->
                        <td style="text-align:left;">{{ text.text }}</td> <!-- Текст -->
                        <td>{{ text.post_dates }}</td><!--Дата проката-->
                        <td>{{ text.quantity_days }}</td> <!--Количество дней-->
                        <td>{{ text.quantity_symbols }}</td> <!--Количество символов-->
                        <td>{{ text.total_price }} сом</td> <!--Сумма -->
                        {% if user.is_staff %}
                            <td>
                                {% if text.reception == False %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-dark">
                                        Не подтвержден
                                    </a>
                                {% else %}
                                    <a style="padding: 0px .75rem;" href="{% url 'change_status' text.id %}"
                                       type="button"
                                       class="btn btn-success">
                                        Подтвержден
                                    </a>
                                {% endif %}
                            </td>
                        {% endif %}
                    </tr>

                {% endif %}
            {% endif %}

        {% endfor %}
        </tbody>
    </table>
    <footer>
        <div class="col-lg-12">
        	<nav class="left-nav">
            {% if is_paginated %}
                <ul class="pagination justify-content-center pagination-sm ">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="link-btn btn btn-primary" href="?page={{ page_obj.previous_page_number }}">Пред.</a></li>

                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                             <li class="page-item"><span class="link-button btn btn-dark"><b>{{ i }} </b></span></li>
                        {% else %}
                            <li class="page-item"><a class="link-button btn btn-primary" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="link-btn btn btn-primary" href="?page={{ page_obj.next_page_number }}">След.</a></li>

                    {% endif %}
                </ul>
            {% endif %}
            </nav>

            <div class="btn-toolbar rigt-nav">
                <div class="btn-group">
                    <a href="{% url 'deletecomplete' %}">
                        <button type="button" class="btn btn-dark">
                            Удалить выделенные
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script>
        function toggle() {
            var div = document.getElementById('pnlDeleteAll');
            if (this.checked)
                div.style.display = 'block';
            else
                div.style.display = 'none'
        }

        document.getElementById('chkDelete').onchange = toggle;
    </script>

    <script>
        function toggle(source) {
            checkboxes = document.getElementsByName('foo');
            for (var i = 0, n = checkboxes.length; i < n; i++) {
                checkboxes[i].checked = source.checked;
            }
        }
    </script>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Login: {{ form.username }}</p>
    <p>Password: {{ form.password1 }}</p>
    <p>Password(repeat): {{ form.password2 }}</p>
    {% if form.password1 != form.password2 %}
    {{ form.code }}
    {% endif %}
    <div class="form-button">
        <button id="submit" type="submit" class="ibtn">Sign up</button>
    </div>
</form>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block title %}
    <h1>TEST</h1>
{% endblock %}
{% block content %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Сохранить</button>
</form>
{% endblock %}